# Generated by Django 5.2.7 on 2025-10-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('kind', models.CharField(choices=[('CKAN', 'CKAN'), ('DATAVERSE', 'Dataverse')], max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('OK', 'OK'), ('ERROR', 'ERROR')], default='PENDING', max_length=10)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_collector.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=191)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('extras', models.JSONField(default=dict)),
                ('created_at_src', models.DateTimeField(blank=True, null=True)),
                ('modified_at_src', models.DateTimeField(blank=True, null=True)),
                ('harvested_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collector.datasource')),
            ],
            options={
                'ordering': ['-harvested_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
