# Generated by Django 5.2.7 on 2025-10-31 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, help_text='q CKAN/Dataverse', max_length=300)),
                ('rows', models.PositiveIntegerField(default=100)),
                ('max_pages', models.PositiveIntegerField(default=5)),
                ('max_items', models.PositiveIntegerField(default=500)),
                ('since', models.DateTimeField(blank=True, help_text='Ignorer plus ancien', null=True)),
                ('incremental', models.BooleanField(default=True, help_text='Utilise last_modified_cursor si dispo')),
                ('enabled', models.BooleanField(default=True)),
                ('schedule', models.CharField(blank=True, help_text='Note libre (ex: 0 2 * * *)', max_length=64)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('PENDING', 'PENDING'), ('OK', 'OK'), ('ERROR', 'ERROR')], default='PENDING', max_length=10)),
                ('last_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_modified_cursor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='organization',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['source', 'harvested_at'], name='data_collec_source__6fe14e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['organization'], name='data_collec_organiz_34876d_idx'),
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collector.datasource'),
        ),
    ]
